# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# Go modules
- package-ecosystem: "gomod"
  directories:
  - "/"
  - "api/hwmgr-plugin"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 5
  groups:
    k8s:
      patterns: [ "k8s.io/*", "sigs.k8s.io/*" ]
      update-types: [ "major", "minor", "patch" ]
    golang:
      patterns: [ "golang.org/*" ]
      update-types: [ "major", "minor", "patch" ]
  ignore:
    # the oran-o2ims version is hand-managed
    - dependency-name: "github.com/openshift-kni/oran-o2ims/api/hardwaremanagement"
    # k8s.io moved to go 1.23 in v0.32, so ignore major/minor updates until this repo is 1.23-based
    - dependency-name: "k8s.io/*"
      update-types: ["version-update:semver-major","version-update:semver-minor"]
    # sigs.k8s.io moved to go 1.23 in v0.20, so ignore major/minor updates until this repo is 1.23-based
    - dependency-name: "sigs.k8s.io/*"
      update-types: ["version-update:semver-major","version-update:semver-minor"]
  #ignore:
  #  - dependency-name: "*"
  #    update-types: ["version-update:semver-patch"]
