apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "hwmgr-plugin.oran.openshift.io/v1alpha1",
          "kind": "HardwareManager",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "oran-hwmgr-plugin",
              "app.kubernetes.io/instance": "hardwaremanager-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "hardwaremanager",
              "app.kubernetes.io/part-of": "oran-hwmgr-plugin"
            },
            "name": "hardwaremanager-sample"
          },
          "spec": {
            "adaptorId": "dell-hwmgr",
            "dellData": {
              "user": "admin"
            }
          },
          "status": {
            "observedGeneration": 1
          }
        }
      ]
    capabilities: Basic Install
    containerImage: registry-proxy.engineering.redhat.com/rh-osbs/openshift4-oran-hwmgr-plugin-rhel9-operator
    description: The O-Cloud Hardware Manager Plugin
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    olm.skipRange: '>=4.16.0 <4.18'
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    operators.operatorframework.io/builder: operator-sdk-v1.38.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    provider: Red Hat
    repository: https://github.com/rauhersu/oran-hwmgr-plugin
    support: Red Hat
  name: oran-hwmgr-plugin.v4.18.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HardwareManager is the Schema for the hardwaremanagers API
      displayName: Hardware Manager
      kind: HardwareManager
      name: hardwaremanagers.hwmgr-plugin.oran.openshift.io
      resources:
      - kind: Service
        name: policy-engine-service
        version: v1
      specDescriptors:
      - description: The adaptor ID
        displayName: Adaptor ID
        path: adaptorId
      - description: Config data for an instance of the dell-hwmgr adaptor
        displayName: Dell Data
        path: dellData
      - displayName: Api Url
        path: dellData.apiUrl
      - displayName: Auth Secret
        path: dellData.authSecret
      - description: |-
          CaBundleName references a config map that contains a set of custom CA certificates to be used when communicating
          with a hardware manager that has its TLS certificate signed by a non-public CA certificate.
        displayName: Custom CA Certificates
        path: dellData.caBundleName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Config data for an instance of the loopback adaptor
        displayName: Loopback Data
        path: loopbackData
      - description: A test string
        displayName: Addtional Info
        path: loopbackData.additionalInfo
      statusDescriptors:
      - description: Conditions describe the state of the UpdateService resource.
        displayName: Conditions
        path: conditions
      - displayName: Observed Generation
        path: observedGeneration
      - description: ResourcePools provides a per-site list of resource pools
        displayName: Resource Pools
        path: resourcePools
      version: v1alpha1
  description: O-Cloud Hardware Manager Plugin
  displayName: O-Cloud Hardware Manager Plugin
  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - hwmgr-plugin.oran.openshift.io
          resources:
          - hardwaremanagers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - hwmgr-plugin.oran.openshift.io
          resources:
          - hardwaremanagers/finalizers
          verbs:
          - update
        - apiGroups:
          - hwmgr-plugin.oran.openshift.io
          resources:
          - hardwaremanagers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - o2ims-hardwaremanagement.oran.openshift.io
          resources:
          - nodepools
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - o2ims-hardwaremanagement.oran.openshift.io
          resources:
          - nodepools/finalizers
          verbs:
          - update
        - apiGroups:
          - o2ims-hardwaremanagement.oran.openshift.io
          resources:
          - nodepools/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - o2ims-hardwaremanagement.oran.openshift.io
          resources:
          - nodes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - o2ims-hardwaremanagement.oran.openshift.io
          resources:
          - nodes/finalizers
          verbs:
          - update
        - apiGroups:
          - o2ims-hardwaremanagement.oran.openshift.io
          resources:
          - nodes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: oran-hwmgr-plugin-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: oran-hwmgr-plugin
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: oran-hwmgr-plugin
          control-plane: controller-manager
        name: oran-hwmgr-plugin-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --v=0
                image: quay.io/openshift/origin-kube-rbac-proxy:4.18
                name: metrics-proxy
                ports:
                - containerPort: 8443
                  name: https-metrics
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --secure-listen-address=0.0.0.0:6443
                - --upstream=http://127.0.0.1:8082/
                - --tls-cert-file=/secrets/tls/tls.crt
                - --tls-private-key-file=/secrets/tls/tls.key
                - --tls-min-version=VersionTLS12
                - --v=0
                image: quay.io/openshift/origin-kube-rbac-proxy:4.18
                name: api-proxy
                ports:
                - containerPort: 6443
                  name: https-api
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                volumeMounts:
                - mountPath: /secrets/tls
                  name: controller-manager-tls
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --api-bind-address=127.0.0.1:8082
                - --leader-elect
                command:
                - /manager
                env:
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: MY_POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/openshift-kni/oran-hwmgr-plugin:4.18.0
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 8080
                  name: metrics
                  protocol: TCP
                - containerPort: 8081
                  name: probes
                  protocol: TCP
                - containerPort: 8082
                  name: api
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: oran-hwmgr-plugin-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: controller-manager-tls
                secret:
                  defaultMode: 256
                  secretName: controller-manager-tls
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: oran-hwmgr-plugin-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - ORAN
  - plugin
  links:
  - name: Oran Hwmgr Plugin
    url: https://oran-hwmgr-plugin.domain
  maintainers:
  - email: dpenney@redhat.com
    name: Don Penney
  maturity: alpha
  minKubeVersion: 1.28.0
  provider:
    name: Red Hat
  replaces: oran-hwmgr-plugin.v0.0.0
  version: 4.18.0
