---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - hwmgr-plugin.oran.openshift.io
  resources:
  - hardwaremanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hwmgr-plugin.oran.openshift.io
  resources:
  - hardwaremanagers/finalizers
  verbs:
  - update
- apiGroups:
  - hwmgr-plugin.oran.openshift.io
  resources:
  - hardwaremanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - o2ims-hardwaremanagement.oran.openshift.io
  resources:
  - nodepools
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - o2ims-hardwaremanagement.oran.openshift.io
  resources:
  - nodepools/finalizers
  verbs:
  - update
- apiGroups:
  - o2ims-hardwaremanagement.oran.openshift.io
  resources:
  - nodepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - o2ims-hardwaremanagement.oran.openshift.io
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - o2ims-hardwaremanagement.oran.openshift.io
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - o2ims-hardwaremanagement.oran.openshift.io
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
