apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    containerImage: registry-proxy.engineering.redhat.com/rh-osbs/openshift4-oran-hwmgr-plugin-rhel9-operator
    description: The O-Cloud Hardware Manager Plugin
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    olm.skipRange: '>=4.16.0 <4.18'
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    operators.operatorframework.io/builder: operator-sdk-v1.35.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    provider: Red Hat
    repository: https://github.com/rauhersu/oran-hwmgr-plugin
    support: Red Hat
  name: oran-hwmgr-plugin.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HardwareManager is the Schema for the hardwaremanagers API
      displayName: Hardware Manager
      kind: HardwareManager
      name: hardwaremanagers.hwmgr-plugin.oran.openshift.io
      resources:
      - kind: Service
        name: policy-engine-service
        version: v1
      specDescriptors:
      - description: The adaptor ID
        displayName: Adaptor ID
        path: adaptorId
      - description: Config data for an instance of the dell-hwmgr adaptor
        displayName: Dell Data
        path: dellData
      - displayName: Api Url
        path: dellData.apiUrl
      - displayName: Auth Secret
        path: dellData.authSecret
      - description: |-
          CaBundleName references a config map that contains a set of custom CA certificates to be used when communicating
          with a hardware manager that has its TLS certificate signed by a non-public CA certificate.
        displayName: Custom CA Certificates
        path: dellData.caBundleName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Config data for an instance of the loopback adaptor
        displayName: Loopback Data
        path: loopbackData
      - description: A test string
        displayName: Addtional Info
        path: loopbackData.additionalInfo
      statusDescriptors:
      - description: Conditions describe the state of the UpdateService resource.
        displayName: Conditions
        path: conditions
      - displayName: Observed Generation
        path: observedGeneration
      - description: ResourcePools provides a per-site list of resource pools
        displayName: Resource Pools
        path: resourcePools
      version: v1alpha1
    - description: HardwareProfile is the Schema for the hardwareprofiles API
      displayName: Hardware Profile
      kind: HardwareProfile
      name: hardwareprofiles.hwmgr-plugin.oran.openshift.io
      resources:
      - kind: Service
        name: policy-engine-service
        version: v1
      specDescriptors:
      - description: Bios defines a set of bios attributes
        displayName: Bios
        path: bios
      - displayName: Attributes
        path: bios.attributes
      - description: BiosVersion is the desired firmware version of BIOS
        displayName: BIOS Version
        path: biosVersion
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: BmcVersion is the desired firmware version of BMC
        displayName: BMC Version
        path: bmcVersion
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - description: Represents the observations of a HardwareProfile's current state
        displayName: Conditions
        path: conditions
      - displayName: Observed Generation
        path: observedGeneration
      version: v1alpha1
  description: O-Cloud Hardware Manager Plugin
  displayName: O-Cloud Hardware Manager Plugin
  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - ORAN
  - plugin
  links:
  - name: Oran Hwmgr Plugin
    url: https://oran-hwmgr-plugin.domain
  maintainers:
  - email: dpenney@redhat.com
    name: Don Penney
  maturity: alpha
  minKubeVersion: 1.28.0
  provider:
    name: Red Hat
  replaces: oran-hwmgr-plugin.v0.0.0
  version: 0.0.1
