apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-client
  namespace: oran-hwmgr-plugin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oran-hwmgr-plugin-test-role
rules:
- nonResourceURLs:
  - /hardware-manager/inventory/*
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oran-hwmgr-plugin-test-client-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oran-hwmgr-plugin-test-role
subjects:
- kind: ServiceAccount
  name: test-client
  namespace: oran-hwmgr-plugin
