apiVersion: o2ims-hardwaremanagement.oran.openshift.io/v1alpha1
kind: NodePool
metadata:
  name: np2
  namespace: oran-hwmgr-plugin
spec:
  cloudID: testcloud-2
  hwMgrId: loopback-2
  location: ottawa
  nodeGroup:
  - hwProfile: profile-spr-single-processor-64G
    name: master
    size: 3
  - hwProfile: profile-spr-dual-processor-128G
    name: worker
    size: 2
  site: building-2
