apiVersion: o2ims-hardwaremanagement.oran.openshift.io/v1alpha1
kind: NodePool
metadata:
  name: np2
  namespace: oran-hwmgr-plugin
spec:
  cloudID: testcloud-2
  hwMgrId: loopback-1
  location: ottawa
  nodeGroup:
  - nodePoolData:
      hwProfile: profile-spr-single-processor-64G
      name: controller
      resourcePoolId: master
      role: master
    size: 3
  - nodePoolData:
      hwProfile: profile-spr-dual-processor-128G
      name: worker
      resourcePoolId: worker
      role: worker
    size: 2
  site: building-2
